const { VITE_ROOT, VITE_API_ROOT, VITE_NAVER_CLIENT_ID, VITE_NAVER_STATE, VITE_GOOGLE_CLIENT_ID, VITE_GOOGLE_SECRET } =
  import.meta.env;

export { VITE_ROOT, VITE_API_ROOT, VITE_NAVER_CLIENT_ID, VITE_NAVER_STATE, VITE_GOOGLE_CLIENT_ID, VITE_GOOGLE_SECRET };
