import { MemberLinkInfo } from '@/types';

// 더미 파일입니다
// TODO : 구현 완료 후 삭제해주세요

// 읽던 글
export const dummyForKeepGoing: MemberLinkInfo[] = [
  {
    member_link_id: '1',
    member_id: '',
    link_id: '',
    member_link_name: '우아한 수다 타임에 작은 기여하기',
    link_url: 'https://www.naver.com/',
    writer: 'Stories by 송요창 on Medium',
    writed_date: '2023.09.11',
    tags: ['우수타'],
    created_at: '0000-00-00 00:00:00',
    updated_at: '0000-00-00 00:00:00',
    deleted_at: null,
    member_link_status: 'In Progress',
  },
  {
    member_link_id: '2',
    member_id: '',
    link_id: '',
    member_link_name: '[발표] 개발자의 학과 습',
    link_url: 'https://www.google.co.kr/',
    writer: 'Korean FE article',
    writed_date: '2023.09.12',
    tags: ['학습', '개발'],
    created_at: '0000-00-00 00:00:00',
    updated_at: '0000-00-00 00:00:00',
    deleted_at: null,
    member_link_status: 'In Progress',
  },
  {
    member_link_id: '3',
    member_id: '',
    link_id: '',
    member_link_name: '타이틀이다 길면 줄이기! 우선 길게 써야지 테스트해야하니까',
    link_url: 'https://ryusoo-h.github.io/myBoard/code-drawer/?post=post2',
    writer: '이름이 길수도 있죠 영어일수도있고 길수도있고',
    writed_date: '2023.10.09',
    tags: ['테스트', 'UI_뚝딱뚝딱', '태그', '개수', '늘리기'],
    created_at: '0000-00-00 00:00:00',
    updated_at: '0000-00-00 00:00:00',
    deleted_at: null,
    member_link_status: 'In Progress',
  },
  {
    member_link_id: '14',
    member_id: '',
    link_id: '',
    member_link_name: '우아한 수다 타임에 작은 기여하기',
    link_url: 'https://www.naver.com/',
    writer: 'Stories by 송요창 on Medium',
    writed_date: '2023.09.11',
    tags: ['우수타'],
    created_at: '0000-00-00 00:00:00',
    updated_at: '0000-00-00 00:00:00',
    deleted_at: null,
    member_link_status: 'In Progress',
  },
  {
    member_link_id: '15',
    member_id: '',
    link_id: '',
    member_link_name: '타이틀이다 길면 줄이기! 우선 길게 써야지 테스트해야하니까',
    link_url: 'https://ryusoo-h.github.io/myBoard/code-drawer/?post=post2',
    writer: '이름이 길수도 있죠 영어일수도있고 길수도있고',
    writed_date: '2023.10.09',
    tags: ['테스트', 'UI_뚝딱뚝딱', '안녕_이제_졸린듯', '시리얼_냠냠', '태그', '개수', '늘리기', '22222'],
    created_at: '0000-00-00 00:00:00',
    updated_at: '0000-00-00 00:00:00',
    deleted_at: null,
    member_link_status: 'In Progress',
  },
];

// 새 글
export const dummyForKeep: MemberLinkInfo[] = [
  {
    member_link_id: '1',
    member_id: '',
    link_id: '',
    member_link_name: '우아한 수다 타임에 작은 기여하기',
    link_url: 'https://www.naver.com/',
    writer: 'Stories by 송요창 on Medium',
    writed_date: '2023.09.11',
    tags: ['우수타'],
    created_at: '0000-00-00 00:00:00',
    updated_at: null,
    deleted_at: null,
    member_link_status: 'Saved',
  },
  {
    member_link_id: '2',
    member_id: '',
    link_id: '',
    member_link_name: '[발표] 개발자의 학과 습',
    link_url: 'https://www.google.co.kr/',
    writer: 'Korean FE article',
    writed_date: '2023.09.12',
    tags: ['학습', '개발'],
    created_at: '0000-00-00 00:00:00',
    updated_at: null,
    deleted_at: null,
    member_link_status: 'Saved',
  },
  {
    member_link_id: '3',
    member_id: '',
    link_id: '',
    member_link_name: '타이틀이다 길면 줄이기! 우선 길게 써야지 테스트해야하니까',
    link_url: 'https://ryusoo-h.github.io/myBoard/code-drawer/?post=post2',
    writer: '이름이 길수도 있죠 영어일수도있고 길수도있고',
    writed_date: '2023.10.09',
    tags: ['테스트', 'UI_뚝딱뚝딱', '태그', '개수', '늘리기'],
    created_at: '0000-00-00 00:00:00',
    updated_at: null,
    deleted_at: null,
    member_link_status: 'Saved',
  },
  {
    member_link_id: '4',
    member_id: '',
    link_id: '',
    member_link_name: '우아한 수다 타임에 작은 기여하기',
    link_url: 'https://www.naver.com/',
    writer: 'Stories by 송요창 on Medium',
    writed_date: '2023.09.11',
    tags: ['우수타'],
    created_at: '0000-00-00 00:00:00',
    updated_at: null,
    deleted_at: null,
    member_link_status: 'Saved',
  },
  {
    member_link_id: '5',
    member_id: '',
    link_id: '',
    member_link_name: '[발표] 개발자의 학과 습',
    link_url: 'https://www.google.co.kr/',
    writer: 'Korean FE article',
    writed_date: '2023.09.12',
    tags: ['학습', '개발'],
    created_at: '0000-00-00 00:00:00',
    updated_at: null,
    deleted_at: null,
    member_link_status: 'Saved',
  },
  {
    member_link_id: '6',
    member_id: '',
    link_id: '',
    member_link_name: '타이틀이다 길면 줄이기! 우선 길게 써야지 테스트해야하니까',
    link_url: 'https://ryusoo-h.github.io/myBoard/code-drawer/?post=post2',
    writer: '이름이 길수도 있죠 영어일수도있고 길수도있고',
    writed_date: '2023.10.09',
    tags: ['테스트', 'UI_뚝딱뚝딱', '태그', '개수', '늘리기'],
    created_at: '0000-00-00 00:00:00',
    updated_at: null,
    deleted_at: null,
    member_link_status: 'Saved',
  },
  {
    member_link_id: '7',
    member_id: '',
    link_id: '',
    member_link_name: '우아한 수다 타임에 작은 기여하기',
    link_url: 'https://www.naver.com/',
    writer: 'Stories by 송요창 on Medium',
    writed_date: '2023.09.11',
    tags: ['우수타'],
    created_at: '0000-00-00 00:00:00',
    updated_at: null,
    deleted_at: null,
    member_link_status: 'Saved',
  },
  {
    member_link_id: '8',
    member_id: '',
    link_id: '',
    member_link_name: '[발표] 개발자의 학과 습',
    link_url: 'https://www.google.co.kr/',
    writer: 'Korean FE article',
    writed_date: '2023.09.12',
    tags: ['학습', '개발'],
    created_at: '0000-00-00 00:00:00',
    updated_at: null,
    deleted_at: null,
    member_link_status: 'Saved',
  },
  {
    member_link_id: '9',
    member_id: '',
    link_id: '',
    member_link_name: '타이틀이다 길면 줄이기! 우선 길게 써야지 테스트해야하니까',
    link_url: 'https://ryusoo-h.github.io/myBoard/code-drawer/?post=post2',
    writer: '이름이 길수도 있죠 영어일수도있고 길수도있고',
    writed_date: '2023.10.09',
    tags: ['테스트', 'UI_뚝딱뚝딱', '태그', '개수', '늘리기'],
    created_at: '0000-00-00 00:00:00',
    updated_at: null,
    deleted_at: null,
    member_link_status: 'Saved',
  },
  {
    member_link_id: '10',
    member_id: '',
    link_id: '',
    member_link_name: '우아한 수다 타임에 작은 기여하기',
    link_url: 'https://www.naver.com/',
    writer: 'Stories by 송요창 on Medium',
    writed_date: '2023.09.11',
    tags: ['우수타'],
    created_at: '0000-00-00 00:00:00',
    updated_at: null,
    deleted_at: null,
    member_link_status: 'Saved',
  },
  {
    member_link_id: '11',
    member_id: '',
    link_id: '',
    member_link_name: '타이틀이다 길면 줄이기! 우선 길게 써야지 테스트해야하니까',
    link_url: 'https://ryusoo-h.github.io/myBoard/code-drawer/?post=post2',
    writer: '이름이 길수도 있죠 영어일수도있고 길수도있고',
    writed_date: '2023.10.09',
    tags: ['테스트', 'UI_뚝딱뚝딱', '안녕_이제_졸린듯', '시리얼_냠냠', '태그', '개수', '늘리기', '22222'],
    created_at: '0000-00-00 00:00:00',
    updated_at: null,
    deleted_at: null,
    member_link_status: 'Saved',
  },
];

// 읽은 글
export const dummyForRead: MemberLinkInfo[] = [
  {
    member_link_id: '11',
    member_id: '',
    link_id: '',
    member_link_name: '우아한 수다 타임에 작은 기여하기',
    link_url: 'https://www.naver.com/',
    writer: 'Stories by 송요창 on Medium',
    writed_date: '2023.09.11',
    tags: ['우수타'],
    created_at: '0000-00-00 00:00:00',
    updated_at: '0000-00-00 00:00:00',
    deleted_at: null,
    member_link_status: 'Completed',
  },
  {
    member_link_id: '12',
    member_id: '',
    link_id: '',
    member_link_name: '[발표] 개발자의 학과 습',
    link_url: 'https://www.google.co.kr/',
    writer: 'Korean FE article',
    writed_date: '2023.09.12',
    tags: ['학습', '개발'],
    created_at: '0000-00-00 00:00:00',
    updated_at: '0000-00-00 00:00:00',
    deleted_at: null,
    member_link_status: 'Completed',
  },
  {
    member_link_id: '13',
    member_id: '',
    link_id: '',
    member_link_name: '타이틀이다 길면 줄이기! 우선 길게 써야지 테스트해야하니까',
    link_url: 'https://ryusoo-h.github.io/myBoard/code-drawer/?post=post2',
    writer: '이름이 길수도 있죠 영어일수도있고 길수도있고',
    writed_date: '2023.10.09',
    tags: ['테스트', 'UI_뚝딱뚝딱', '태그', '개수', '늘리기'],
    created_at: '0000-00-00 00:00:00',
    updated_at: '0000-00-00 00:00:00',
    deleted_at: null,
    member_link_status: 'Completed',
  },
  {
    member_link_id: '14',
    member_id: '',
    link_id: '',
    member_link_name: '우아한 수다 타임에 작은 기여하기',
    link_url: 'https://www.naver.com/',
    writer: 'Stories by 송요창 on Medium',
    writed_date: '2023.09.11',
    tags: ['우수타'],
    created_at: '0000-00-00 00:00:00',
    updated_at: '0000-00-00 00:00:00',
    deleted_at: null,
    member_link_status: 'Completed',
  },
  {
    member_link_id: '15',
    member_id: '',
    link_id: '',
    member_link_name: '타이틀이다 길면 줄이기! 우선 길게 써야지 테스트해야하니까',
    link_url: 'https://ryusoo-h.github.io/myBoard/code-drawer/?post=post2',
    writer: '이름이 길수도 있죠 영어일수도있고 길수도있고',
    writed_date: '2023.10.09',
    tags: ['테스트', 'UI_뚝딱뚝딱', '안녕_이제_졸린듯', '시리얼_냠냠', '태그', '개수', '늘리기', '22222'],
    created_at: '0000-00-00 00:00:00',
    updated_at: '0000-00-00 00:00:00',
    deleted_at: null,
    member_link_status: 'Completed',
  },
];

// 모든 글
export const dummyForAll: MemberLinkInfo[] = [];
