import { LinkInfo } from '@/types';

// 더미 파일입니다
// TODO : 구현 완료 후 삭제해주세요

// 읽던 글
export const dummyForKeepGoing: LinkInfo[] = [
  {
    id: 1,
    title: '우아한 수다 타임에 작은 기여하기',
    url: 'https://www.naver.com/',
    writer: 'Stories by 송요창 on Medium',
    writeDate: '2023.09.11',
    tags: ['우수타'],
    createdAt: '0000.00.00',
    updatedAt: '0000.00.00',
    status: false,
  },
  {
    id: 2,
    title: '[발표] 개발자의 학과 습',
    url: 'https://www.google.co.kr/',
    writer: 'Korean FE article',
    writeDate: '2023.09.12',
    tags: ['학습', '개발'],
    createdAt: '0000.00.00',
    updatedAt: '0000.00.00',
    status: false,
  },
  {
    id: 3,
    title: '타이틀이다 길면 줄이기! 우선 길게 써야지 테스트해야하니까',
    url: 'https://ryusoo-h.github.io/myBoard/code-drawer/?post=post2',
    writer: '이름이 길수도 있죠 영어일수도있고 길수도있고',
    writeDate: '2023.10.09',
    tags: ['테스트', 'UI_뚝딱뚝딱', '태그', '개수', '늘리기'],
    createdAt: '0000.00.00',
    updatedAt: '0000.00.00',
    status: false,
  },
  {
    id: 14,
    title: '우아한 수다 타임에 작은 기여하기',
    url: 'https://www.naver.com/',
    writer: 'Stories by 송요창 on Medium',
    writeDate: '2023.09.11',
    tags: ['우수타'],
    createdAt: '0000.00.00',
    updatedAt: '0000.00.00',
    status: false,
  },
  {
    id: 15,
    title: '타이틀이다 길면 줄이기! 우선 길게 써야지 테스트해야하니까',
    url: 'https://ryusoo-h.github.io/myBoard/code-drawer/?post=post2',
    writer: '이름이 길수도 있죠 영어일수도있고 길수도있고',
    writeDate: '2023.10.09',
    tags: ['테스트', 'UI_뚝딱뚝딱', '안녕_이제_졸린듯', '시리얼_냠냠', '태그', '개수', '늘리기', '22222'],
    createdAt: '0000.00.00',
    updatedAt: '0000.00.00',
    status: false,
  },
];

// 새 글
export const dummyForKeep: LinkInfo[] = [
  {
    id: 1,
    title: '우아한 수다 타임에 작은 기여하기',
    url: 'https://www.naver.com/',
    writer: 'Stories by 송요창 on Medium',
    writeDate: '2023.09.11',
    tags: ['우수타'],
    createdAt: '0000.00.00',
    updatedAt: null,
    status: false,
  },
  {
    id: 2,
    title: '[발표] 개발자의 학과 습',
    url: 'https://www.google.co.kr/',
    writer: 'Korean FE article',
    writeDate: '2023.09.12',
    tags: ['학습', '개발'],
    createdAt: '0000.00.00',
    updatedAt: null,
    status: false,
  },
  {
    id: 3,
    title: '타이틀이다 길면 줄이기! 우선 길게 써야지 테스트해야하니까',
    url: 'https://ryusoo-h.github.io/myBoard/code-drawer/?post=post2',
    writer: '이름이 길수도 있죠 영어일수도있고 길수도있고',
    writeDate: '2023.10.09',
    tags: ['테스트', 'UI_뚝딱뚝딱', '태그', '개수', '늘리기'],
    createdAt: '0000.00.00',
    updatedAt: null,
    status: false,
  },
  {
    id: 4,
    title: '우아한 수다 타임에 작은 기여하기',
    url: 'https://www.naver.com/',
    writer: 'Stories by 송요창 on Medium',
    writeDate: '2023.09.11',
    tags: ['우수타'],
    createdAt: '0000.00.00',
    updatedAt: null,
    status: false,
  },
  {
    id: 5,
    title: '[발표] 개발자의 학과 습',
    url: 'https://www.google.co.kr/',
    writer: 'Korean FE article',
    writeDate: '2023.09.12',
    tags: ['학습', '개발'],
    createdAt: '0000.00.00',
    updatedAt: null,
    status: false,
  },
  {
    id: 6,
    title: '타이틀이다 길면 줄이기! 우선 길게 써야지 테스트해야하니까',
    url: 'https://ryusoo-h.github.io/myBoard/code-drawer/?post=post2',
    writer: '이름이 길수도 있죠 영어일수도있고 길수도있고',
    writeDate: '2023.10.09',
    tags: ['테스트', 'UI_뚝딱뚝딱', '태그', '개수', '늘리기'],
    createdAt: '0000.00.00',
    updatedAt: null,
    status: false,
  },
  {
    id: 7,
    title: '우아한 수다 타임에 작은 기여하기',
    url: 'https://www.naver.com/',
    writer: 'Stories by 송요창 on Medium',
    writeDate: '2023.09.11',
    tags: ['우수타'],
    createdAt: '0000.00.00',
    updatedAt: null,
    status: false,
  },
  {
    id: 8,
    title: '[발표] 개발자의 학과 습',
    url: 'https://www.google.co.kr/',
    writer: 'Korean FE article',
    writeDate: '2023.09.12',
    tags: ['학습', '개발'],
    createdAt: '0000.00.00',
    updatedAt: null,
    status: false,
  },
  {
    id: 9,
    title: '타이틀이다 길면 줄이기! 우선 길게 써야지 테스트해야하니까',
    url: 'https://ryusoo-h.github.io/myBoard/code-drawer/?post=post2',
    writer: '이름이 길수도 있죠 영어일수도있고 길수도있고',
    writeDate: '2023.10.09',
    tags: ['테스트', 'UI_뚝딱뚝딱', '태그', '개수', '늘리기'],
    createdAt: '0000.00.00',
    updatedAt: null,
    status: false,
  },
  {
    id: 10,
    title: '우아한 수다 타임에 작은 기여하기',
    url: 'https://www.naver.com/',
    writer: 'Stories by 송요창 on Medium',
    writeDate: '2023.09.11',
    tags: ['우수타'],
    createdAt: '0000.00.00',
    updatedAt: null,
    status: false,
  },
  {
    id: 11,
    title: '타이틀이다 길면 줄이기! 우선 길게 써야지 테스트해야하니까',
    url: 'https://ryusoo-h.github.io/myBoard/code-drawer/?post=post2',
    writer: '이름이 길수도 있죠 영어일수도있고 길수도있고',
    writeDate: '2023.10.09',
    tags: ['테스트', 'UI_뚝딱뚝딱', '안녕_이제_졸린듯', '시리얼_냠냠', '태그', '개수', '늘리기', '22222'],
    createdAt: '0000.00.00',
    updatedAt: null,
    status: false,
  },
];

// 읽은 글
export const dummyForRead: LinkInfo[] = [
  {
    id: 11,
    title: '우아한 수다 타임에 작은 기여하기',
    url: 'https://www.naver.com/',
    writer: 'Stories by 송요창 on Medium',
    writeDate: '2023.09.11',
    tags: ['우수타'],
    createdAt: '0000.00.00',
    updatedAt: '0000.00.00',
    status: true,
  },
  {
    id: 12,
    title: '[발표] 개발자의 학과 습',
    url: 'https://www.google.co.kr/',
    writer: 'Korean FE article',
    writeDate: '2023.09.12',
    tags: ['학습', '개발'],
    createdAt: '0000.00.00',
    updatedAt: '0000.00.00',
    status: true,
  },
  {
    id: 13,
    title: '타이틀이다 길면 줄이기! 우선 길게 써야지 테스트해야하니까',
    url: 'https://ryusoo-h.github.io/myBoard/code-drawer/?post=post2',
    writer: '이름이 길수도 있죠 영어일수도있고 길수도있고',
    writeDate: '2023.10.09',
    tags: ['테스트', 'UI_뚝딱뚝딱', '태그', '개수', '늘리기'],
    createdAt: '0000.00.00',
    updatedAt: '0000.00.00',
    status: true,
  },
  {
    id: 14,
    title: '우아한 수다 타임에 작은 기여하기',
    url: 'https://www.naver.com/',
    writer: 'Stories by 송요창 on Medium',
    writeDate: '2023.09.11',
    tags: ['우수타'],
    createdAt: '0000.00.00',
    updatedAt: '0000.00.00',
    status: true,
  },
  {
    id: 15,
    title: '타이틀이다 길면 줄이기! 우선 길게 써야지 테스트해야하니까',
    url: 'https://ryusoo-h.github.io/myBoard/code-drawer/?post=post2',
    writer: '이름이 길수도 있죠 영어일수도있고 길수도있고',
    writeDate: '2023.10.09',
    tags: ['테스트', 'UI_뚝딱뚝딱', '안녕_이제_졸린듯', '시리얼_냠냠', '태그', '개수', '늘리기', '22222'],
    createdAt: '0000.00.00',
    updatedAt: '0000.00.00',
    status: true,
  },
];

// 모든 글
export const dummyForAll: LinkInfo[] = [
  {
    id: 1,
    title: '우아한 수다 타임에 작은 기여하기',
    url: 'https://www.naver.com/',
    writer: 'Stories by 송요창 on Medium',
    writeDate: '2023.09.11',
    tags: ['우수타'],
    createdAt: '0000.00.00',
    updatedAt: null,
    status: false,
  },
  {
    id: 2,
    title: '[발표] 개발자의 학과 습',
    url: 'https://www.google.co.kr/',
    writer: 'Korean FE article',
    writeDate: '2023.09.12',
    tags: ['학습', '개발'],
    createdAt: '0000.00.00',
    updatedAt: null,
    status: false,
  },
  {
    id: 3,
    title: '타이틀이다 길면 줄이기! 우선 길게 써야지 테스트해야하니까',
    url: 'https://ryusoo-h.github.io/myBoard/code-drawer/?post=post2',
    writer: '이름이 길수도 있죠 영어일수도있고 길수도있고',
    writeDate: '2023.10.09',
    tags: ['테스트', 'UI_뚝딱뚝딱', '안녕_이제_졸린듯', '시리얼_냠냠', '태그', '개수', '늘리기', '22222'],
    createdAt: '0000.00.00',
    updatedAt: '0000.00.00',
    status: true,
  },
  {
    id: 4,
    title: '우아한 수다 타임에 작은 기여하기',
    url: 'https://www.naver.com/',
    writer: 'Stories by 송요창 on Medium',
    writeDate: '2023.09.11',
    tags: ['우수타'],
    createdAt: '0000.00.00',
    updatedAt: null,
    status: false,
  },
  {
    id: 5,
    title: '[발표] 개발자의 학과 습',
    url: 'https://www.google.co.kr/',
    writer: 'Korean FE article',
    writeDate: '2023.09.12',
    tags: ['학습', '개발'],
    createdAt: '0000.00.00',
    updatedAt: '0000.00.00',
    status: false,
  },
  {
    id: 6,
    title: '타이틀이다 길면 줄이기! 우선 길게 써야지 테스트해야하니까',
    url: 'https://ryusoo-h.github.io/myBoard/code-drawer/?post=post2',
    writer: '이름이 길수도 있죠 영어일수도있고 길수도있고',
    writeDate: '2023.10.09',
    tags: ['테스트', 'UI_뚝딱뚝딱', '안녕_이제_졸린듯', '시리얼_냠냠', '태그', '개수', '늘리기', '22222'],
    createdAt: '0000.00.00',
    updatedAt: '0000.00.00',
    status: true,
  },
  {
    id: 7,
    title: '[발표] 개발자의 학과 습',
    url: 'https://www.google.co.kr/',
    writer: 'Korean FE article',
    writeDate: '2023.09.12',
    tags: ['테스트', 'UI_뚝딱뚝딱', '태그', '개수', '늘리기'],
    createdAt: '0000.00.00',
    updatedAt: '0000.00.00',
    status: true,
  },
  {
    id: 8,
    title: '우아한 수다 타임에 작은 기여하기',
    url: 'https://www.naver.com/',
    writer: 'Stories by 송요창 on Medium',
    writeDate: '2023.09.11',
    tags: ['우수타'],
    createdAt: '0000.00.00',
    updatedAt: '0000.00.00',
    status: true,
  },
  {
    id: 9,
    title: '우아한 수다 타임에 작은 기여하기',
    url: 'https://www.naver.com/',
    writer: 'Stories by 송요창 on Medium',
    writeDate: '2023.09.11',
    tags: ['우수타'],
    createdAt: '0000.00.00',
    updatedAt: null,
    status: false,
  },
  {
    id: 10,
    title: '[발표] 개발자의 학과 습',
    url: 'https://www.google.co.kr/',
    writer: 'Korean FE article',
    writeDate: '2023.09.12',
    tags: ['학습', '개발'],
    createdAt: '0000.00.00',
    updatedAt: null,
    status: false,
  },
  {
    id: 11,
    title: '타이틀이다 길면 줄이기! 우선 길게 써야지 테스트해야하니까',
    url: 'https://ryusoo-h.github.io/myBoard/code-drawer/?post=post2',
    writer: '이름이 길수도 있죠 영어일수도있고 길수도있고',
    writeDate: '2023.10.09',
    tags: ['테스트', 'UI_뚝딱뚝딱', '안녕_이제_졸린듯', '시리얼_냠냠', '태그', '개수', '늘리기', '22222'],
    createdAt: '0000.00.00',
    updatedAt: '0000.00.00',
    status: true,
  },
  {
    id: 12,
    title: '우아한 수다 타임에 작은 기여하기',
    url: 'https://www.naver.com/',
    writer: 'Stories by 송요창 on Medium',
    writeDate: '2023.09.11',
    tags: ['우수타'],
    createdAt: '0000.00.00',
    updatedAt: null,
    status: false,
  },
  {
    id: 13,
    title: '[발표] 개발자의 학과 습',
    url: 'https://www.google.co.kr/',
    writer: 'Korean FE article',
    writeDate: '2023.09.12',
    tags: ['학습', '개발'],
    createdAt: '0000.00.00',
    updatedAt: '0000.00.00',
    status: false,
  },
  {
    id: 14,
    title: '타이틀이다 길면 줄이기! 우선 길게 써야지 테스트해야하니까',
    url: 'https://ryusoo-h.github.io/myBoard/code-drawer/?post=post2',
    writer: '이름이 길수도 있죠 영어일수도있고 길수도있고',
    writeDate: '2023.10.09',
    tags: ['테스트', 'UI_뚝딱뚝딱', '안녕_이제_졸린듯', '시리얼_냠냠', '태그', '개수', '늘리기', '22222'],
    createdAt: '0000.00.00',
    updatedAt: '0000.00.00',
    status: true,
  },
  {
    id: 15,
    title: '[발표] 개발자의 학과 습',
    url: 'https://www.google.co.kr/',
    writer: 'Korean FE article',
    writeDate: '2023.09.12',
    tags: ['테스트', 'UI_뚝딱뚝딱', '태그', '개수', '늘리기'],
    createdAt: '0000.00.00',
    updatedAt: '0000.00.00',
    status: true,
  },
  {
    id: 19,
    title: '우아한 수다 타임에 작은 기여하기',
    url: 'https://www.naver.com/',
    writer: 'Stories by 송요창 on Medium',
    writeDate: '2023.09.11',
    tags: ['우수타'],
    createdAt: '0000.00.00',
    updatedAt: '0000.00.00',
    status: true,
  },
  {
    id: 20,
    title: '우아한 수다 타임에 작은 기여하기',
    url: 'https://www.naver.com/',
    writer: 'Stories by 송요창 on Medium',
    writeDate: '2023.09.11',
    tags: ['우수타'],
    createdAt: '0000.00.00',
    updatedAt: null,
    status: false,
  },
  {
    id: 21,
    title: '[발표] 개발자의 학과 습',
    url: 'https://www.google.co.kr/',
    writer: 'Korean FE article',
    writeDate: '2023.09.12',
    tags: ['학습', '개발'],
    createdAt: '0000.00.00',
    updatedAt: null,
    status: false,
  },
  {
    id: 22,
    title: '타이틀이다 길면 줄이기! 우선 길게 써야지 테스트해야하니까',
    url: 'https://ryusoo-h.github.io/myBoard/code-drawer/?post=post2',
    writer: '이름이 길수도 있죠 영어일수도있고 길수도있고',
    writeDate: '2023.10.09',
    tags: ['테스트', 'UI_뚝딱뚝딱', '안녕_이제_졸린듯', '시리얼_냠냠', '태그', '개수', '늘리기', '22222'],
    createdAt: '0000.00.00',
    updatedAt: '0000.00.00',
    status: true,
  },
  {
    id: 23,
    title: '우아한 수다 타임에 작은 기여하기',
    url: 'https://www.naver.com/',
    writer: 'Stories by 송요창 on Medium',
    writeDate: '2023.09.11',
    tags: ['우수타'],
    createdAt: '0000.00.00',
    updatedAt: null,
    status: false,
  },
  {
    id: 24,
    title: '[발표] 개발자의 학과 습',
    url: 'https://www.google.co.kr/',
    writer: 'Korean FE article',
    writeDate: '2023.09.12',
    tags: ['학습', '개발'],
    createdAt: '0000.00.00',
    updatedAt: '0000.00.00',
    status: false,
  },
  {
    id: 25,
    title: '타이틀이다 길면 줄이기! 우선 길게 써야지 테스트해야하니까',
    url: 'https://ryusoo-h.github.io/myBoard/code-drawer/?post=post2',
    writer: '이름이 길수도 있죠 영어일수도있고 길수도있고',
    writeDate: '2023.10.09',
    tags: ['테스트', 'UI_뚝딱뚝딱', '안녕_이제_졸린듯', '시리얼_냠냠', '태그', '개수', '늘리기', '22222'],
    createdAt: '0000.00.00',
    updatedAt: '0000.00.00',
    status: true,
  },
  {
    id: 26,
    title: '[발표] 개발자의 학과 습',
    url: 'https://www.google.co.kr/',
    writer: 'Korean FE article',
    writeDate: '2023.09.12',
    tags: ['테스트', 'UI_뚝딱뚝딱', '태그', '개수', '늘리기'],
    createdAt: '0000.00.00',
    updatedAt: '0000.00.00',
    status: true,
  },
  {
    id: 27,
    title: '우아한 수다 타임에 작은 기여하기',
    url: 'https://www.naver.com/',
    writer: 'Stories by 송요창 on Medium',
    writeDate: '2023.09.11',
    tags: ['우수타'],
    createdAt: '0000.00.00',
    updatedAt: '0000.00.00',
    status: true,
  },
  {
    id: 28,
    title: '우아한 수다 타임에 작은 기여하기',
    url: 'https://www.naver.com/',
    writer: 'Stories by 송요창 on Medium',
    writeDate: '2023.09.11',
    tags: ['우수타'],
    createdAt: '0000.00.00',
    updatedAt: null,
    status: false,
  },
  {
    id: 29,
    title: '[발표] 개발자의 학과 습',
    url: 'https://www.google.co.kr/',
    writer: 'Korean FE article',
    writeDate: '2023.09.12',
    tags: ['학습', '개발'],
    createdAt: '0000.00.00',
    updatedAt: null,
    status: false,
  },
  {
    id: 30,
    title: '타이틀이다 길면 줄이기! 우선 길게 써야지 테스트해야하니까',
    url: 'https://ryusoo-h.github.io/myBoard/code-drawer/?post=post2',
    writer: '이름이 길수도 있죠 영어일수도있고 길수도있고',
    writeDate: '2023.10.09',
    tags: ['테스트', 'UI_뚝딱뚝딱', '안녕_이제_졸린듯', '시리얼_냠냠', '태그', '개수', '늘리기', '22222'],
    createdAt: '0000.00.00',
    updatedAt: '0000.00.00',
    status: true,
  },
  {
    id: 31,
    title: '우아한 수다 타임에 작은 기여하기',
    url: 'https://www.naver.com/',
    writer: 'Stories by 송요창 on Medium',
    writeDate: '2023.09.11',
    tags: ['우수타'],
    createdAt: '0000.00.00',
    updatedAt: null,
    status: false,
  },
  {
    id: 32,
    title: '[발표] 개발자의 학과 습',
    url: 'https://www.google.co.kr/',
    writer: 'Korean FE article',
    writeDate: '2023.09.12',
    tags: ['학습', '개발'],
    createdAt: '0000.00.00',
    updatedAt: '0000.00.00',
    status: false,
  },
  {
    id: 33,
    title: '타이틀이다 길면 줄이기! 우선 길게 써야지 테스트해야하니까',
    url: 'https://ryusoo-h.github.io/myBoard/code-drawer/?post=post2',
    writer: '이름이 길수도 있죠 영어일수도있고 길수도있고',
    writeDate: '2023.10.09',
    tags: ['테스트', 'UI_뚝딱뚝딱', '안녕_이제_졸린듯', '시리얼_냠냠', '태그', '개수', '늘리기', '22222'],
    createdAt: '0000.00.00',
    updatedAt: '0000.00.00',
    status: true,
  },
  {
    id: 34,
    title: '[발표] 개발자의 학과 습',
    url: 'https://www.google.co.kr/',
    writer: 'Korean FE article',
    writeDate: '2023.09.12',
    tags: ['테스트', 'UI_뚝딱뚝딱', '태그', '개수', '늘리기'],
    createdAt: '0000.00.00',
    updatedAt: '0000.00.00',
    status: true,
  },
  {
    id: 35,
    title: '우아한 수다 타임에 작은 기여하기',
    url: 'https://www.naver.com/',
    writer: 'Stories by 송요창 on Medium',
    writeDate: '2023.09.11',
    tags: ['우수타'],
    createdAt: '0000.00.00',
    updatedAt: '0000.00.00',
    status: true,
  },
  {
    id: 39,
    title: '우아한 수다 타임에 작은 기여하기',
    url: 'https://www.naver.com/',
    writer: 'Stories by 송요창 on Medium',
    writeDate: '2023.09.11',
    tags: ['우수타'],
    createdAt: '0000.00.00',
    updatedAt: null,
    status: false,
  },
  {
    id: 40,
    title: '[발표] 개발자의 학과 습',
    url: 'https://www.google.co.kr/',
    writer: 'Korean FE article',
    writeDate: '2023.09.12',
    tags: ['학습', '개발'],
    createdAt: '0000.00.00',
    updatedAt: null,
    status: false,
  },
  {
    id: 41,
    title: '타이틀이다 길면 줄이기! 우선 길게 써야지 테스트해야하니까',
    url: 'https://ryusoo-h.github.io/myBoard/code-drawer/?post=post2',
    writer: '이름이 길수도 있죠 영어일수도있고 길수도있고',
    writeDate: '2023.10.09',
    tags: ['테스트', 'UI_뚝딱뚝딱', '안녕_이제_졸린듯', '시리얼_냠냠', '태그', '개수', '늘리기', '22222'],
    createdAt: '0000.00.00',
    updatedAt: '0000.00.00',
    status: true,
  },
  {
    id: 42,
    title: '우아한 수다 타임에 작은 기여하기',
    url: 'https://www.naver.com/',
    writer: 'Stories by 송요창 on Medium',
    writeDate: '2023.09.11',
    tags: ['우수타'],
    createdAt: '0000.00.00',
    updatedAt: null,
    status: false,
  },
  {
    id: 43,
    title: '[발표] 개발자의 학과 습',
    url: 'https://www.google.co.kr/',
    writer: 'Korean FE article',
    writeDate: '2023.09.12',
    tags: ['학습', '개발'],
    createdAt: '0000.00.00',
    updatedAt: '0000.00.00',
    status: false,
  },
  {
    id: 44,
    title: '타이틀이다 길면 줄이기! 우선 길게 써야지 테스트해야하니까',
    url: 'https://ryusoo-h.github.io/myBoard/code-drawer/?post=post2',
    writer: '이름이 길수도 있죠 영어일수도있고 길수도있고',
    writeDate: '2023.10.09',
    tags: ['테스트', 'UI_뚝딱뚝딱', '안녕_이제_졸린듯', '시리얼_냠냠', '태그', '개수', '늘리기', '22222'],
    createdAt: '0000.00.00',
    updatedAt: '0000.00.00',
    status: true,
  },
  {
    id: 45,
    title: '[발표] 개발자의 학과 습',
    url: 'https://www.google.co.kr/',
    writer: 'Korean FE article',
    writeDate: '2023.09.12',
    tags: ['테스트', 'UI_뚝딱뚝딱', '태그', '개수', '늘리기'],
    createdAt: '0000.00.00',
    updatedAt: '0000.00.00',
    status: true,
  },
  {
    id: 465,
    title: '우아한 수다 타임에 작은 기여하기',
    url: 'https://www.naver.com/',
    writer: 'Stories by 송요창 on Medium',
    writeDate: '2023.09.11',
    tags: ['우수타'],
    createdAt: '0000.00.00',
    updatedAt: '0000.00.00',
    status: true,
  },
];
